FROM python:3.4

MAINTAINER PyKMIP-Team

ENV PYTHONUNBUFFERED 1

COPY ./requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt

COPY ./test-requirements.txt /app/test-requirements.txt
RUN pip install -r /app/test-requirements.txt

COPY ./ /app
RUN cd /app/ && python setup.py build && python setup.py install
